### DISCUSSION TITLE
colors v2

### DISCUSSION THREAD

**Discussion by KutnerUri** [teambit/harmony-base-ui#14] [Ideas]
I want to improve our color variables. We've got a couple of problems:
- Variables are global and mix with out Consumers' styles → add `--bit-` prefix.
  ( ⚠️ important!)
- The term 'highlight' is confusing → rename to 'heavy', and introduce 'light'
- The term 'base' implies default. → rename to 'accent'
- The term 'muted' is confusing → rename to 'bg-accent'
- Background names are no good → rename to `bg-01`, `bg-02`, up to 05 etc
  - keep `bg-tooltip`, `bg-bedrock`, `bg-dent`

Extra:
- Update `DarkMod` to use new colors
- Update `color palette` component and rename to be `accent themes`

## Breaking changes
Renaming these variables is a breaking change - any code that relies on them will fallback to default.

I'm thinking of doing this in two tags:
1. add new variables (minor version)
2. remove the old variables (major version)

## TODO
- [ ] add new colors, tag (minor version)
- [ ] remove old colors, tag (major version)
- [ ] update all existing components, using find-and-replace
  - [ ]  base-ui
  - [ ] evangelist
  - [ ] documenter
  - [ ] bit-bin (repo)
  - [ ] symphony (repo)
- [ ] Update consumers to use the new component version

## Next colors

```
.colors {
    color: $d50;
    --bit-text-color-heavy: #{$d60};
    --bit-text-color: #{$d50};
    --bit-text-color-light: #{$d40};

    --bit-border-color-heavy: #{$d30};
    --bit-border-color: #{$d20};
    --bit-border-color-light: #{$d10};	

    // accent:
    --bit-accent-color: #{$p50};
    --bit-accent-highlight: #{$p60};
	
    --bit-accent-bg: {$p20};
    --bit-accent-bg-heavy: {$p30};

   // background:	
    --bit-bg-color: #{$w10};
    --bit-bg-bedrock: #{$w10};  // i.e. <body/> background
    --bit-bg-navigation: #{$w10};     // e.g. navigation
    --bit-bg-tooltip: #{$w10};  // e.g. button, input, etc
    --bit-bg-tooltip-heavy: #{$w20};
    --bit-bg-dent: #{$w20};

    // might replace with 'error' theme
    --bit-error-color: #{$r50};
    --bit-error-highlight: #{$r60};
    --bit-bg-error: #{$r20};
}
```

## Previous colors 

```scss
.colors {
	color: $d50;
	--text-highlight: #{$d60};
	--text-color: #{$d50};
	--text-muted: #{$d40};
	--steel-color: #{$d30}; // (!)

	--base-color: #{$p50};
	--base-highlight: #{$p60};

	--border-color: #{$d10};
	--bg-color: #{$w10};
	--separator-color: #{$d20};

	--muted-color: #{$p20}; //unsettled
	--muted-highlight: #{$p30}; //unsettled

	--error-color: #{$r50};
	--error-highlight: #{$r60};
	--bg-error: #{$r20};

	--bg-bedrock: #{$w10};  // i.e. <body/> background
	--bg-base: #{$w10};     // e.g. navigation
	--bg-layer: #{$w10};    // e.g. card
	--bg-crust: #{$w10};    // e.g. tooltip    
	--bg-topping: #{$w10};  // e.g. button, input, etc
	--bg-topping-highlight: #{$w20};
	--bg-dent: #{$w20};
}
```

## Accent color
![image](https://user-images.githubusercontent.com/5400361/114002711-c807b800-9865-11eb-8a2c-5d4f735ef7ed.png)
> "Accent colors are colors that are used for emphasis in a color scheme."
